M48
; DRILL file {KiCad 8.0.0} date 2024-03-22T20:52:53+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-22T20:52:53+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0295
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1575
%
G90
G05
T1
X4.4823Y-3.6671
X4.7106Y-3.6671
T2
X4.3648Y-3.0164
X4.6153Y-3.2669
T3
X4.0725Y-2.7241
X4.0725Y-3.5592
X4.9077Y-2.7241
X4.9077Y-3.5592
M30
